line-length = 88
target-version = "py312"

lint.select = ["ALL"]
lint.ignore = ["ASYNC210", "B008", "COM812", "D100", "D101", "D102", "D103", "D104", "D107", "D203", "D212", "PLR0913", "PTH100", "PTH118", "PTH120", "PTH123", "S311"]

lint.per-file-ignores = {"tests/*.py" = ["ALL"], "main.py" = ["ARG001"]}