"""
add_logo_to_company_model.

Revision ID: 769091755878
Revises: db3da66edca3
Create Date: 2025-10-20 16:43:10.850973

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "769091755878"
down_revision: str | Sequence[str] | None = "db3da66edca3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("token_blacklist")
    op.add_column(
        "company", sa.Column("logo", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("company", "logo")
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("jti", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "expires_at",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("token_blacklist_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("token_blacklist_pkey")),
        sa.UniqueConstraint("jti", name=op.f("token_blacklist_jti_key")),
    )
    # ### end Alembic commands ###
