"""add user payment customer id

Revision ID: eb9c8606b961
Revises: e81afe08ce96
Create Date: 2025-11-05 00:51:00.728885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb9c8606b961"
down_revision: Union[str, Sequence[str], None] = "e81afe08ce96"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_payment", sa.Column("customer_id", sa.String(), nullable=True))
    op.add_column("user_payment", sa.Column("start_date", sa.Float(), nullable=False))
    op.add_column("user_payment", sa.Column("end_date", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_payment", "end_date")
    op.drop_column("user_payment", "start_date")
    op.drop_column("user_payment", "customer_id")
    # ### end Alembic commands ###
